### ISSUE TITLE
Broken on Python 3.10

### ISSUE THREAD

**Issue by FichteFoll** [FichteFoll/discordrp-mpris#26]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 287, in main
    return loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 280, in main_async
    return await instance.run()
  File "/usr/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 67, in run
    await self.connect_discord()
  File "/usr/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 56, in connect_discord
    await self.discord.connect()
  File "/usr/lib/python3.10/site-packages/discord_rpc/async_.py", line 63, in connect
    await self._connect()
  File "/usr/lib/python3.10/site-packages/discord_rpc/async_.py", line 216, in _connect
    await asyncio.open_unix_connection(path, loop=self.loop)
  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/discordrp-mpris", line 33, in <module>
    sys.exit(load_entry_point('discordrp-mpris==0.3.0', 'console_scripts', 'discordrp-mpris')())
  File "/usr/lib/python3.10/site-packages/discordrp_mpris/__main__.py", line 290, in main
    wait_task = asyncio.wait_for(main_task, 5, loop=loop)
TypeError: wait_for() got an unexpected keyword argument 'loop'
```

**Comment by CrazyMagicians** [comment]
I've got the same bug now how do i fix it?
